spring:
  datasource:
    url: jdbc:postgres://kgrwjvdakhynhm:97cabb3a7c49ed0e7891ae95441be0a0eebd5a7ac5fe5fb0e7cbf76b4533943c@ec2-54-80-122-11.compute-1.amazonaws.com:5432/d690flqtsbhmrr
    username: kgrwjvdakhynhm
    password: 97cabb3a7c49ed0e7891ae95441be0a0eebd5a7ac5fe5fb0e7cbf76b4533943c
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: romijatmiko033@gmail.com
    password: vjvccruvgqowfrsw
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false